# Local development profile — matches docker-compose postgres service
spring.datasource.url=jdbc:postgresql://localhost:5432/reservare_db
spring.datasource.username=reservare
spring.datasource.password=reservare

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

logging.level.md.usm.teza.reservare=DEBUG
 
# JWT
app.jwt.secret=812569ffd2eef62ab61e057ea04503995896d5a15fb0270d96af4be1473bcabe
app.jwt.expiration-ms=360000